### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by thellef** [dundalek/atom-markdown-mindmap#1]
I ruun 1.04 on Windows 7 and get this when installing:

Installing “markdown-mindmap@0.1.2” failed.Hide output…

> runas@2.0.0 install C:\Users\tel\AppData\Local\Temp\apm-install-dir-11575-9240-1t37jf\node_modules\markdown-mindmap\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild

C:\Users\tel\AppData\Local\Temp\apm-install-dir-11575-9240-1t37jf\node_modules\markdown-mindmap\node_modules\pathwatcher\node_modules\runas>node "C:\Users\tel\AppData\Local\atom\app-1.0.4\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\tel\\AppData\\Local\\atom\\app-1.0.4\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\tel\\AppData\\Local\\atom\\app-1.0.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\tel\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\tel\\.atom\\.apmrc" "install" "C:\\Users\\tel\\AppData\\Local\\Temp\\d-11575-9240-k46j9p\\package.tgz" "--target=0.22.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

**Comment by dundalek** [comment]
Hi, it fails because of the `runas` package which is using `node-gyp`, see issue https://github.com/atom/node-runas/issues/11. Make sure you have all dependencies listed [here](https://github.com/TooTallNate/node-gyp). The try `npm install runas` in an empty directory. If that succeeds than the package will install inside Atom. There is also a discussion with some tips here: https://github.com/Galadirith/markdown-preview-plus/issues/43

**Comment by Gaoura** [comment]
I got the same problem, I tried to resolve it with your links but I still got the problem, markdown-preview-plus doesn't install because of `runas` too :3

**Comment by dundalek** [comment]
I removed the pathwatcher dependency, since it is already included in atom core. The package now installs without the need of extra dependencies mentioned above. I tested it on Windows 7.
