### ISSUE TITLE
Failed to load the markdown-mindmap package

### ISSUE THREAD

**Issue by tx19851107** [dundalek/atom-markdown-mindmap#10]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [markdown-mindmap](https://github.com/dundalek/atom-markdown-mindmap) package, v0.2.4
### Stack Trace

Failed to load the markdown-mindmap package

```
At '../node_modules/markmap/view.mindmap.css' wasn't found in C:\Users\wbnju\.atom\packages\atom-markdown-mindmap-master\styles\markdown-mindmap.less:1:0

LessError: '../node_modules/markmap/view.mindmap.css' wasn't found
  at C:\Users\wbnju\.atom\packages\atom-markdown-mindmap-master\styles\markdown-mindmap.less:1:0
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "base16-tomorrow-light-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
node-v0.36.8, vundefined

# Dev
No dev packages
```

**Comment by dundalek** [comment]
Tried to install it in latest Atom on Windows 7 and it works. Reinstalling the plugin should solve it.
