### ISSUE TITLE
preview mode

### ISSUE THREAD

**Issue by ROBsoer** [dundalek/atom-markdown-mindmap#12]
As we know **markdawn** has two modes: editing and previewing. Preview mode looks great for re-read documents.
But now click on the node tree refers to the section in edit document mode. It would be great to use your plugin for navigation in preview too.

Thank you for your work.

**Comment by dundalek** [comment]
There is an outstanding issue for this to be implemented in the preview plugin (see https://github.com/atom/markdown-preview/issues/24). As a workaround installing the [markdown-scroll-sync](https://atom.io/packages/markdown-scroll-sync) plugin should enable this.

**Comment by dundalek** [comment]
I recommend using [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) plugin which syncs the scroll position of the preview automatically and works well with the mindmap navigation.
