### ISSUE TITLE
feature of saving mindmap as a eps or png file.

### ISSUE THREAD

**Issue by coolboy0961** [dundalek/atom-markdown-mindmap#14]
Thank you for your work.
This is a amazing atom plunig.

I want to save my mindmap as a eps or png file,then I can share it to my colleague.

**Comment by dundalek** [comment]
You can now save it as SVG (see https://github.com/dundalek/atom-markdown-mindmap/issues/5 for details). You can then convert it to png or eps with an external utility. I will not likely implement these additional formats, but a PR is welcome.
