### ISSUE TITLE
Size of node should adapt to content

### ISSUE THREAD

**Issue by kindlychung** [dundalek/atom-markdown-mindmap#24]
Example:

```markdown
# Theorem
## Branch 1
### Step 1
#### $x^2 + y^2$
### Step 2 with a very long long long long long long long long long long 
### Step 3
## Branch 2
### Step 1
### Step 2
### Step 3
## Branch 3
### Step 1
### Step 2
### Step 3
```

![](https://i.imgur.com/hvWqLX2.png)

**Comment by dundalek** [comment]
Definitely, we need a better layouting algorithm. I created an issue to track progress: https://github.com/dundalek/markmap/issues/11

**Comment by dundalek** [comment]
This is now supported in the new version `0.4.0`. It adapts width to the content. By default it truncates long labels and you get result like this:

![image](https://user-images.githubusercontent.com/755611/29752358-b307e462-8b5c-11e7-8b43-aa4b32adacac.png)

But you can also turn off truncation in settings and you will get this:

![image](https://user-images.githubusercontent.com/755611/29752366-d32bd01e-8b5c-11e7-8ea0-fee06c18b557.png)
