### ISSUE TITLE
Add support for treating line/list as node

### ISSUE THREAD

**Issue by secfree** [dundalek/atom-markdown-mindmap#27]
As https://github.com/dundalek/markmap/blob/master/examples/example.txtmap, a file with headers such as

```
# level 101
## level 201
### level 301
#### level 401
## level 202
### level 302
#### level 402
```

can be simplified as

```
- level 101
    - level 201
        - level 301
            - level 401
    - level 202
        - level 302
            - level 402
```

or 

```
level 101
    level 201
        level 301
            level 401
    level 202
        level 302
            level 402
```

which would have a clear hierarchy and avoiding to input a lot of `#` chars.

**Comment by dundalek** [comment]
This is now supported in the new version `0.4.0`. You can use dashes like in your first example, or you can use asterisks (`*`) for lists as well. From your example you get this:

![image](https://user-images.githubusercontent.com/755611/29752302-b528c5c8-8b5b-11e7-8ab4-422639ee8b27.png)
