### ISSUE TITLE
Block size for capital letters

### ISSUE THREAD

**Issue by ejdazhi** [dundalek/atom-markdown-mindmap#29]
block size is fit for lower letters, but is not enough for same capital letters .
my system is ubuntu 16.04.

![image](https://user-images.githubusercontent.com/16408364/30148627-dd244c86-93d6-11e7-98de-354775c4bec9.png)

![image](https://user-images.githubusercontent.com/16408364/30148584-b8d5e740-93d6-11e7-8ad8-64c096f3d867.png)

PS: your tool is cool !!!

**Comment by dundalek** [comment]
Thanks for the report, good catch. This needs fixing, I will look into it.

**Comment by dundalek** [comment]
I just published a quick fix (v0.4.1) to maker more space for capital letters. Eventually we probably want to render each text into a element and measure its dimensions, but this should work alright in the meantime.

![image](https://user-images.githubusercontent.com/755611/30216349-03c237ea-94b3-11e7-92f2-d3a3952065d1.png)
