### ISSUE TITLE
Numeric List wrong!

### ISSUE THREAD

**Issue by rasperepodvipodvert** [dundalek/atom-markdown-mindmap#31]
![default](https://user-images.githubusercontent.com/14201321/30797352-5c9c7654-a1de-11e7-97cb-60eb4d6598c0.png)

**Comment by dundalek** [comment]
Good catch, numeric lists seem to be broken. I don't use them often so I haven't test those, will look into it.

**Comment by dundalek** [comment]
Fixed in the latest version v0.4.2.
