### ISSUE TITLE
AtomEnvironment.showSaveDialogSync is deprecated.

### ISSUE THREAD

**Issue by echo-ray** [dundalek/atom-markdown-mindmap#37]
Hi~ @dundalek 

Thanks for your to provide such an amazing tools  that we can write markdown file and render it to mind map immediately.

That is really convenient to store important knowledges.

Actually, I'm a vs code user, and I was trying to find such a tool in vs code, but I failed. Fortunately, I accidentally found your project recently. It works well in Atom.

Thank you very much~!
__________
Here I wanna report a small issue that Atom always reminds me.
I'm a newfish in Atom, so I'm not sure if this would matter in the future.
Sorry to bother you about this.

______
atom.showSaveDialogSync is deprecated and will be removed soon.
      Please, implement ::saveAs and ::getSaveDialogOptions instead for pane items
      or use Pane::saveItemAs for programmatic saving.
```
AtomEnvironment.showSaveDialogSync (<embedded>:1438:11)
MarkdownMindmapView.saveAs (/Users/ray/.atom/packages/markdown-mindmap/lib/markdown-mindmap-view.coffee:470:31)
HTMLDivElement.atom.commands.add.core:save-as (/Users/ray/.atom/packages/markdown-mindmap/lib/markdown-mindmap-view.coffee:161:26)
CommandRegistry.handleCommandEvent (<embedded>:23906:49)
CommandRegistry.dispatch (<embedded>:23795:23)
AtomEnvironment.dispatchContextMenuCommand (<embedded>:1591:25)
```

**Comment by dundalek** [comment]
Thanks for letting me know, I haven't noticed that. You are right, this might cause issues in the future, I will look into it.
