### ISSUE TITLE
Add option to use UI theme as mindmap theme

### ISSUE THREAD

**Issue by nlsn** [dundalek/atom-markdown-mindmap#4]
I'm using One Dark as my UI theme, so both the default and colorful mindmap themes are quite bright.

Would it be possible to add an option to the mindmap themes list to use the general Atom UI theme? Something like unchecking the "Use GitHub.com style" option in the core Markdown Preview settings.

Thanks!

**Comment by dundalek** [comment]
Hi, thanks for your suggestion. I have no idea how to extract colors from Atom's UI themes. Are you more familiar with the theme system, is it possible somehow?

However, what I could do is to create dark variants of the current themes. It would probably not match given UI exactly, but it should be more comfortable. What do you think?

**Comment by nlsn** [comment]
I would love that! Thanks!

**Comment by nlsn** [comment]
Sorry I don't have any insight into how the Atom UI themes work. Just a noob user with Atom.

**Comment by dundalek** [comment]
Sounds good, I will get to it in the next couple of days.

**Comment by dundalek** [comment]
Added in 0.2.4, after you upgrade the package you will be able to switch to dark themes in package settings.

**Comment by nlsn** [comment]
Looks great! Much easier on my eyes.

I appreciate your efforts, friend. Thanks.

**Comment by dundalek** [comment]
Cool, glad you like it.
