### ISSUE TITLE
Export as SVG

### ISSUE THREAD

**Issue by dundalek** [dundalek/atom-markdown-mindmap#5]
Possible variants:
- copy to clipboard
- save as a file

**Comment by ccschmitz** [comment]
This would be awesome!

**Comment by dundalek** [comment]
I am looking into this. There is a bit of challenge because CSS is used for styling. There are two possible solutions:

1. Hardcode the styling into elements directly - but we would loose flexibility when creating various themes.
2. Find out a way how to inline those styles into DOM before exporting.

**Comment by DSigmund** [comment]
Also save as png would be a good start ;-)
or autosave ;-)

**Comment by sander76** [comment]
I'd love to see any export option too !

**Comment by dundalek** [comment]
This is now implemented in v0.3.0 update.

To export an SVG image right click on the mindmap and select copy or save from the menu:
![image](https://cloud.githubusercontent.com/assets/755611/21986433/bd99bb56-dbff-11e6-87f8-f0f06631055e.png)
