### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by ChrisChinchilla** [dundalek/atom-markdown-mindmap#9]
Keen to try this plugin, but when running the command nothing happens, no errors either.

How can I help debug what's going on?

**Comment by viegelinsch** [comment]
Same here.

Atom 1.10.0
OS X 10.11.16

**Comment by thchung** [comment]
Mindmap Toggle works when the file is not yet saved, but as soon as the Markdown file is saved, the toggle no longer appears to do anything (i.e., render).

Atom 1.10.2
OS X 10.11.6

**Comment by floriandierickx** [comment]
Same here (no reaction)

Atom 1.12.5
OS X 10.12.1

**Comment by floriandierickx** [comment]
Maybe this points to a solution (?), but for me it didn't work out:
```
brew install node
sudo npm install npm -g
npm init markmap
npm install markmap
```

**Comment by floriandierickx** [comment]
I have the same issue as @thchung 

Atom 1.12.5
OS X 10.12.1

**Comment by dubravcik** [comment]
Same here

**Comment by ChrisChinchilla** [comment]
I can confirm that the comment from @dubravcik solves my problem, I will close this issue and comment there.
